# Generated by Django 2.0.3 on 2018-03-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('typeOfEgg', models.CharField(max_length=100)),
                ('sizeOfEgg', models.CharField(max_length=100)),
            ],
        ),
    ]
